### ISSUE TITLE
Purge/cleanup option?

### ISSUE THREAD

**Issue by AaronHolbrook** [lkwdwrd/generator-vvv#54]
Would be nice to have a command to go through and cleanup a site/ remove itself from everywhere it's installed at. Not sure if that'd be too dangerous or not, but would certainly be nice while testing since it adds itself to:

* mysql db
* nginx config
* /etc/hosts on vm
* general files on machine

**Comment by lkwdwrd** [comment]
This actually already exists, but is a grunt workflow.

It's been a little fuzzy headed toward v1 since some site management tools for a site after creation have moved to the generator (e.g. adding a new plugin), but in general, site creation tools are in the generator, and site management, including cleanup, is done in grunt. You can run `grunt cleanup` and it will make a db snap shot and clean the install out of VVV for you leaving you with any DB dumps and a json file. I generally refer to this as 'dehydrated' state.

**Comment by AaronHolbrook** [comment]
Ah, that's pretty cool!
